# Generated by Django 4.2.8 on 2023-12-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNumber', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('YourAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('description', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
