# Generated by Django 4.2.8 on 2023-12-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
