# Generated by Django 4.2.8 on 2023-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_delivery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
